<a href="https://colab.research.google.com/github/Soni-20/TKM/blob/main/numpyarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
list=[1,2,3]
print(list)
array1=np.array(list)
print(array1)
list2=([10,20,30],[40,50,60])
print(list2)
array2=np.array(list2)
print(array2)

[1, 2, 3]
[1 2 3]
([10, 20, 30], [40, 50, 60])
[[10 20 30]
 [40 50 60]]


In [14]:

x=np.arange(1,20)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [16]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [19]:
np.arange(1,20)
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones(5)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [27]:
np.random.rand(5)

array([0.1255389 , 0.81248115, 0.6499106 , 0.72793803, 0.11326744])

In [29]:
np.random.randn(5)

array([-0.11624144,  0.18837854,  0.42365447, -1.4585299 , -0.39534322])

In [31]:
np.random.randint(1,100)

75

In [33]:
new_arr=np.random.randint(1,100,10)

In [35]:
new_arr

array([36,  7, 71, 38, 39,  5, 62, 55, 94, 29])

In [37]:
new_arr.shape

(10,)

In [49]:
new_arr.shape

(10,)

In [50]:
new_arr.reshape(10,1)

array([[36],
       [ 7],
       [71],
       [38],
       [39],
       [ 5],
       [62],
       [55],
       [94],
       [29]])

In [51]:
new_arr.argmax()

8

In [53]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr_2d[1][1]

5

In [69]:
arr_2d[1:2]

array([[4, 5, 6]])

In [71]:
arr_2d[2:3]

array([[7, 8, 9]])

In [80]:
arr_2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [76]:
bool_arr=arr>8

NameError: ignored